tasks:
  - init: docker run --rm --interactive --tty --volume $PWD:/app composer install && sudo apt-get update && sudo apt-get install yq
ports:
  - port: 3000
    onOpen: notify
    visibility: public