name: "Build and Deploy OpenRuntimes Images"

on:
  release:
    types: [published]

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Node
          - runtimes: node-21.js
            RUNTIME: node-21.0
            ENTRYPOINT: tests.js
            IMAGE: openruntimes/node:v3-21.0
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "npm install"
            OPEN_RUNTIMES_START_COMMAND: "pm2 start src/server.js --no-daemon"
          - runtimes: node-20.js
            RUNTIME: node-20.0
            ENTRYPOINT: tests.js
            IMAGE: openruntimes/node:v3-20.0
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "npm install"
            OPEN_RUNTIMES_START_COMMAND: "pm2 start src/server.js --no-daemon"
          - runtimes: node-19.js
            RUNTIME: node-19.0
            ENTRYPOINT: tests.js
            IMAGE: openruntimes/node:v3-19.0
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "npm install"
            OPEN_RUNTIMES_START_COMMAND: "pm2 start src/server.js --no-daemon"
          - runtimes: node-18.js
            RUNTIME: node-18.0
            ENTRYPOINT: tests.js
            IMAGE: openruntimes/node:v3-18.0
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "npm install"
            OPEN_RUNTIMES_START_COMMAND: "pm2 start src/server.js --no-daemon"
          - runtimes: node-16.js
            RUNTIME: node-16.0
            ENTRYPOINT: tests.js
            IMAGE: openruntimes/node:v3-16.0
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "npm install"
            OPEN_RUNTIMES_START_COMMAND: "pm2 start src/server.js --no-daemon"
          - runtimes: node-14.5.js
            RUNTIME: node-14.5
            ENTRYPOINT: tests.js
            IMAGE: openruntimes/node:v3-14.5
            ARCH: "linux/amd64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "npm install"
            OPEN_RUNTIMES_START_COMMAND: "pm2 start src/server.js --no-daemon"

          # Deno
          - runtimes: deno-1.40
            RUNTIME: deno-1.40
            ENTRYPOINT: tests.ts
            IMAGE: openruntimes/deno:v3-1.40
            ARCH: "linux/amd64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "deno cache tests.ts"
            OPEN_RUNTIMES_START_COMMAND: "denon start"
          - runtimes: deno-1.35
            RUNTIME: deno-1.35
            ENTRYPOINT: tests.ts
            IMAGE: openruntimes/deno:v3-1.35
            ARCH: "linux/amd64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "deno cache tests.ts"
            OPEN_RUNTIMES_START_COMMAND: "denon start"
          - runtimes: deno-1.24
            RUNTIME: deno-1.24
            ENTRYPOINT: tests.ts
            IMAGE: openruntimes/deno:v3-1.24
            ARCH: "linux/amd64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "deno cache tests.ts"
            OPEN_RUNTIMES_START_COMMAND: "denon start"
          - runtimes: deno-1.21
            RUNTIME: deno-1.21
            ENTRYPOINT: tests.ts
            IMAGE: openruntimes/deno:v3-1.21
            ARCH: "linux/amd64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "deno cache tests.ts"
            OPEN_RUNTIMES_START_COMMAND: "denon start"

          # Python
          - runtimes: python-3.12
            RUNTIME: python-3.12
            ENTRYPOINT: tests.py
            IMAGE: openruntimes/python:v3-3.11
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "pip install --no-cache-dir -r requirements.txt"
            OPEN_RUNTIMES_START_COMMAND: "python3 src/server.py"
          - runtimes: python-3.11
            RUNTIME: python-3.11
            ENTRYPOINT: tests.py
            IMAGE: openruntimes/python:v3-3.11
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "pip install --no-cache-dir -r requirements.txt"
            OPEN_RUNTIMES_START_COMMAND: "python3 src/server.py"
          - runtimes: python-3.10
            RUNTIME: python-3.10
            ENTRYPOINT: tests.py
            IMAGE: openruntimes/python:v3-3.10
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "pip install --no-cache-dir -r requirements.txt"
            OPEN_RUNTIMES_START_COMMAND: "python3 src/server.py"
          - runtimes: python-3.9
            RUNTIME: python-3.9
            ENTRYPOINT: tests.py
            IMAGE: openruntimes/python:v3-3.9
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "pip install --no-cache-dir -r requirements.txt"
            OPEN_RUNTIMES_START_COMMAND: "python3 src/server.py"
          - runtimes: python-3.8
            RUNTIME: python-3.8
            ENTRYPOINT: tests.py
            IMAGE: openruntimes/python:v3-3.8
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "pip install --no-cache-dir -r requirements.txt"
            OPEN_RUNTIMES_START_COMMAND: "python3 src/server.py"

          # Python ML
          - runtimes: python-ml-3.11
            RUNTIME: python-ml-3.11
            ENTRYPOINT: tests.py
            IMAGE: openruntimes/python-ml:v3-3.11
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "pip install --no-cache-dir -r requirements.txt"
            OPEN_RUNTIMES_START_COMMAND: "python3 src/server.py"

          # Dart
          - runtimes: dart-3.3
            RUNTIME: dart-3.3
            ENTRYPOINT: lib/tests.dart
            IMAGE: openruntimes/dart:v3-3.3
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "dart pub get"
            OPEN_RUNTIMES_START_COMMAND: "src/function/server"
          - runtimes: dart-3.1
            RUNTIME: dart-3.1
            ENTRYPOINT: lib/tests.dart
            IMAGE: openruntimes/dart:v3-3.1
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "dart pub get"
            OPEN_RUNTIMES_START_COMMAND: "src/function/server"
          - runtimes: dart-3.0
            RUNTIME: dart-3.0
            ENTRYPOINT: lib/tests.dart
            IMAGE: openruntimes/dart:v3-3.0
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "dart pub get"
            OPEN_RUNTIMES_START_COMMAND: "src/function/server"
          - runtimes: dart-2.19
            RUNTIME: dart-2.19
            ENTRYPOINT: lib/tests.dart
            IMAGE: openruntimes/dart:v3-2.19
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "dart pub get"
            OPEN_RUNTIMES_START_COMMAND: "src/function/server"
          - runtimes: dart-2.18
            RUNTIME: dart-2.18
            ENTRYPOINT: lib/tests.dart
            IMAGE: openruntimes/dart:v3-2.18
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "dart pub get"
            OPEN_RUNTIMES_START_COMMAND: "src/function/server"
          - runtimes: dart-2.17
            RUNTIME: dart-2.17
            ENTRYPOINT: lib/tests.dart
            IMAGE: openruntimes/dart:v3-2.17
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "dart pub get"
            OPEN_RUNTIMES_START_COMMAND: "src/function/server"
          - runtimes: dart-2.16
            RUNTIME: dart-2.16
            ENTRYPOINT: lib/tests.dart
            IMAGE: openruntimes/dart:v3-2.16
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "dart pub get"
            OPEN_RUNTIMES_START_COMMAND: "src/function/server"
          - runtimes: dart-2.15
            RUNTIME: dart-2.15
            ENTRYPOINT: lib/tests.dart
            IMAGE: openruntimes/dart:v3-2.15
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "dart pub get"
            OPEN_RUNTIMES_START_COMMAND: "src/function/server"

          # Ruby
          - runtimes: ruby-3.3
            RUNTIME: ruby-3.3
            ENTRYPOINT: tests.rb
            IMAGE: openruntimes/ruby:v3-3.3
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "bundle exec puma -b tcp://0.0.0.0:3000 -e production"
          - runtimes: ruby-3.2
            RUNTIME: ruby-3.2
            ENTRYPOINT: tests.rb
            IMAGE: openruntimes/ruby:v3-3.2
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "bundle exec puma -b tcp://0.0.0.0:3000 -e production"
          - runtimes: ruby-3.1
            RUNTIME: ruby-3.1
            ENTRYPOINT: tests.rb
            IMAGE: openruntimes/ruby:v3-3.1
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "bundle exec puma -b tcp://0.0.0.0:3000 -e production"
          - runtimes: ruby-3.0
            RUNTIME: ruby-3.0
            ENTRYPOINT: tests.rb
            IMAGE: openruntimes/ruby:v3-3.0
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "bundle exec puma -b tcp://0.0.0.0:3000 -e production"

          # PHP
          - runtimes: php-8.3
            RUNTIME: php-8.3
            ENTRYPOINT: tests.php
            IMAGE: openruntimes/php:v3-8.3
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "composer update --no-interaction --ignore-platform-reqs --optimize-autoloader --prefer-dist --no-dev"
            OPEN_RUNTIMES_START_COMMAND: "php src/server.php"
          - runtimes: php-8.2
            RUNTIME: php-8.2
            ENTRYPOINT: tests.php
            IMAGE: openruntimes/php:v3-8.2
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "composer update --no-interaction --ignore-platform-reqs --optimize-autoloader --prefer-dist --no-dev"
            OPEN_RUNTIMES_START_COMMAND: "php src/server.php"
          - runtimes: php-8.1
            RUNTIME: php-8.1
            ENTRYPOINT: tests.php
            IMAGE: openruntimes/php:v3-8.1
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "composer update --no-interaction --ignore-platform-reqs --optimize-autoloader --prefer-dist --no-dev"
            OPEN_RUNTIMES_START_COMMAND: "php src/server.php"
          - runtimes: php-8.0
            RUNTIME: php-8.0
            ENTRYPOINT: tests.php
            IMAGE: openruntimes/php:v3-8.0
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "composer update --no-interaction --ignore-platform-reqs --optimize-autoloader --prefer-dist --no-dev"
            OPEN_RUNTIMES_START_COMMAND: "php src/server.php"

          # Swift
          - runtimes: swift-5.9
            RUNTIME: swift-5.9
            ENTRYPOINT: Tests.swift
            IMAGE: openruntimes/swift:v3-5.9
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "src/function/Runtime serve --env production --hostname 0.0.0.0 --port 3000"
          - runtimes: swift-5.8
            RUNTIME: swift-5.8
            ENTRYPOINT: Tests.swift
            IMAGE: openruntimes/swift:v3-5.8
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "src/function/Runtime serve --env production --hostname 0.0.0.0 --port 3000"
          - runtimes: swift-5.5
            RUNTIME: swift-5.5
            ENTRYPOINT: Tests.swift
            IMAGE: openruntimes/swift:v3-5.5
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "src/function/Runtime serve --env production --hostname 0.0.0.0 --port 3000"

          # Kotlin
          - runtimes: kotlin-1.9
            RUNTIME: kotlin-1.9
            ENTRYPOINT: Tests.kt
            IMAGE: openruntimes/kotlin:v3-1.9
            ARCH: "linux/amd64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "java -jar src/function/kotlin-runtime-1.0.0.jar"
          - runtimes: kotlin-1.8
            RUNTIME: kotlin-1.8
            ENTRYPOINT: Tests.kt
            IMAGE: openruntimes/kotlin:v3-1.8
            ARCH: "linux/amd64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "java -jar src/function/kotlin-runtime-1.0.0.jar"
          - runtimes: kotlin-1.6
            RUNTIME: kotlin-1.6
            ENTRYPOINT: Tests.kt
            IMAGE: openruntimes/kotlin:v3-1.6
            ARCH: "linux/amd64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "java -jar src/function/kotlin-runtime-1.0.0.jar"

          # Java
          - runtimes: java-21.0
            RUNTIME: java-21.0
            ENTRYPOINT: Tests.java
            IMAGE: openruntimes/java:v3-21.0
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "java -jar src/function/java-runtime-1.0.0.jar"
          - runtimes: java-18.0
            RUNTIME: java-18.0
            ENTRYPOINT: Tests.java
            IMAGE: openruntimes/java:v3-18.0
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "java -jar src/function/java-runtime-1.0.0.jar"
          - runtimes: java-17.0
            RUNTIME: java-17.0
            ENTRYPOINT: Tests.java
            IMAGE: openruntimes/java:v3-17.0
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "java -jar src/function/java-runtime-1.0.0.jar"
          - runtimes: java-11.0
            RUNTIME: java-11.0
            ENTRYPOINT: Tests.java
            IMAGE: openruntimes/java:v3-11.0
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "java -jar src/function/java-runtime-1.0.0.jar"
          - runtimes: java-8.0
            RUNTIME: java-8.0
            ENTRYPOINT: Tests.java
            IMAGE: openruntimes/java:v3-8.0
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "java -jar src/function/java-runtime-1.0.0.jar"

          # C++
          - runtimes: cpp-20
            RUNTIME: cpp-20
            ENTRYPOINT: tests.cc
            IMAGE: openruntimes/cpp:v3-20
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "src/function/cpp_runtime"
          - runtimes: cpp-17
            RUNTIME: cpp-17
            ENTRYPOINT: tests.cc
            IMAGE: openruntimes/cpp:v3-17
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "src/function/cpp_runtime"

          # Dotnet
          - runtimes: dotnet-8.0
            RUNTIME: dotnet-8.0
            ENTRYPOINT: Tests.cs
            IMAGE: openruntimes/dotnet:v3-8.0
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "dotnet src/function/DotNetRuntime.dll"
          - runtimes: dotnet-7.0
            RUNTIME: dotnet-7.0
            ENTRYPOINT: Tests.cs
            IMAGE: openruntimes/dotnet:v3-7.0
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "dotnet src/function/DotNetRuntime.dll"
          - runtimes: dotnet-6.0
            RUNTIME: dotnet-6.0
            ENTRYPOINT: Tests.cs
            IMAGE: openruntimes/dotnet:v3-6.0
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "dotnet src/function/DotNetRuntime.dll"

          # Bun
          - runtimes: bun-1.0
            RUNTIME: bun-1.0
            ENTRYPOINT: tests.ts
            IMAGE: openruntimes/bun:v3-1.0
            ARCH: "linux/amd64,linux/arm64"
            TEST_CLASS: "Base"
            OPEN_RUNTIMES_BUILD_COMMAND: "bun install"
            OPEN_RUNTIMES_START_COMMAND: "bun src/server.ts"
    name: ${{ matrix.runtimes }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      - name: Build & Publish to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./runtimes/${{ matrix.RUNTIME }}/
          platforms: ${{ matrix.ARCH }}
          build-args: |
            VERSION=${{ matrix.IMAGE }}
          push: true
          tags: ${{ matrix.IMAGE }}
