# !WARNING: This workflow is only for development purposes.
# Please remove it before merging to main.

name: "Build and Deploy Workspace Image"

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ID: workspace-1
            RUNTIME: workspace
            VERSION: "1"
            IMAGE: openruntimes/workspace:v5-1
            ARCH: "linux/amd64,linux/arm64"

    name: ${{ matrix.ID }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      - name: Prepare runtime folder
        working-directory: ./
        run: |
          bash ./ci_release.sh
        env:
          RUNTIME: ${{ matrix.RUNTIME }}
          ENTRYPOINT: ${{ matrix.ENTRYPOINT }}
          VERSION: ${{ matrix.VERSION }}
          INSTALL_COMMAND: ${{ matrix.INSTALL_COMMAND }}
          START_COMMAND: ${{ matrix.START_COMMAND }}
      - name: Build & Publish to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./runtimes/.test
          platforms: ${{ matrix.ARCH }}
          build-args: |
            VERSION=${{ matrix.IMAGE }}
          push: true
          tags: ${{ matrix.IMAGE }}
