name: "Testing OpenRuntimes"

on: [ pull_request ]

jobs:
  open-runtimes:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Node
          - ID: node-21.0
            RUNTIME: node
            VERSION: "21.0"
            ENTRYPOINT: tests.js
            INSTALL_COMMAND: "npm install"
            START_COMMAND: "pm2 start src/server.js --no-daemon"
          - ID: node-21.0-mjs
            RUNTIME: node
            VERSION: "21.0"
            ENTRYPOINT: tests.mjs
            INSTALL_COMMAND: "npm install"
            START_COMMAND: "pm2 start src/server.js --no-daemon"
          - ID: node-20.0
            RUNTIME: node
            VERSION: "20.0"
            ENTRYPOINT: tests.js
            INSTALL_COMMAND: "npm install"
            START_COMMAND: "pm2 start src/server.js --no-daemon"
          - ID: node-20.0-mjs
            RUNTIME: node
            VERSION: "20.0"
            ENTRYPOINT: tests.mjs
            INSTALL_COMMAND: "npm install"
            START_COMMAND: "pm2 start src/server.js --no-daemon"
          - ID: node-19.0
            RUNTIME: node
            VERSION: "19.0"
            ENTRYPOINT: tests.js
            INSTALL_COMMAND: "npm install"
            START_COMMAND: "pm2 start src/server.js --no-daemon"
          - ID: node-19.0-mjs
            RUNTIME: node
            VERSION: "19.0"
            ENTRYPOINT: tests.mjs
            INSTALL_COMMAND: "npm install"
            START_COMMAND: "pm2 start src/server.js --no-daemon"
          - ID: node-18.0
            RUNTIME: node
            VERSION: "18.0"
            ENTRYPOINT: tests.js
            INSTALL_COMMAND: "npm install"
            START_COMMAND: "pm2 start src/server.js --no-daemon"
          - ID: node-18.0-mjs
            RUNTIME: node
            VERSION: "18.0"
            ENTRYPOINT: tests.mjs
            INSTALL_COMMAND: "npm install"
            START_COMMAND: "pm2 start src/server.js --no-daemon"
          - ID: node-16.0
            RUNTIME: node
            VERSION: "16.0"
            ENTRYPOINT: tests.js
            INSTALL_COMMAND: "npm install"
            START_COMMAND: "pm2 start src/server.js --no-daemon"
          - ID: node-16.0-mjs
            RUNTIME: node
            VERSION: "16.0"
            ENTRYPOINT: tests.mjs
            INSTALL_COMMAND: "npm install"
            START_COMMAND: "pm2 start src/server.js --no-daemon"
          - ID: node-14.5
            VERSION: "14.5"
            RUNTIME: node
            ENTRYPOINT: tests.js
            INSTALL_COMMAND: "npm install"
            START_COMMAND: "pm2 start src/server.js --no-daemon"
          - ID: node-14.5-mjs
            RUNTIME: node
            VERSION: "14.5"
            ENTRYPOINT: tests.mjs
            INSTALL_COMMAND: "npm install"
            START_COMMAND: "pm2 start src/server.js --no-daemon"

          # Deno
          - ID: deno-1.40
            RUNTIME: deno
            VERSION: "1.40"
            ENTRYPOINT: tests.ts
            INSTALL_COMMAND: "deno cache tests.ts"
            START_COMMAND: "denon start"
          - ID: deno-1.35
            RUNTIME: deno
            VERSION: "1.35"
            ENTRYPOINT: tests.ts
            INSTALL_COMMAND: "deno cache tests.ts"
            START_COMMAND: "denon start"
          - ID: deno-1.24
            RUNTIME: deno
            VERSION: "1.24"
            ENTRYPOINT: tests.ts
            INSTALL_COMMAND: "deno cache tests.ts"
            START_COMMAND: "denon start"
          - ID: deno-1.21
            RUNTIME: deno
            VERSION: "1.21"
            ENTRYPOINT: tests.ts
            INSTALL_COMMAND: "deno cache tests.ts"
            START_COMMAND: "denon start"

          # Python
          - runtimes: python-3.12
            RUNTIME: python-3.12
            ENTRYPOINT: tests.py
            IMAGE: openruntimes/python:v4-3.12
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: "pip install --no-cache-dir -r requirements.txt"
            OPEN_RUNTIMES_START_COMMAND: "python3 src/server.py"
          - runtimes: python-3.11
            RUNTIME: python-3.11
            ENTRYPOINT: tests.py
            IMAGE: openruntimes/python:v4-3.11
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: "pip install --no-cache-dir -r requirements.txt"
            OPEN_RUNTIMES_START_COMMAND: "python3 src/server.py"
          - runtimes: python-3.10
            RUNTIME: python-3.10
            ENTRYPOINT: tests.py
            IMAGE: openruntimes/python:v4-3.10
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: "pip install --no-cache-dir -r requirements.txt"
            OPEN_RUNTIMES_START_COMMAND: "python3 src/server.py"
          - runtimes: python-3.9
            RUNTIME: python-3.9
            ENTRYPOINT: tests.py
            IMAGE: openruntimes/python:v4-3.9
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: "pip install --no-cache-dir -r requirements.txt"
            OPEN_RUNTIMES_START_COMMAND: "python3 src/server.py"
          - runtimes: python-3.8
            RUNTIME: python-3.8
            ENTRYPOINT: tests.py
            IMAGE: openruntimes/python:v4-3.8
            ARCH: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: "pip install --no-cache-dir -r requirements.txt"
            OPEN_RUNTIMES_START_COMMAND: "python3 src/server.py"

          # Python ML
          - runtimes: python-ml-3.11
            RUNTIME: python-ml-3.11
            ENTRYPOINT: tests.py
            IMAGE: openruntimes/python-ml:v4-3.11
            ARCH: "linux/amd64,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: "pip install --no-cache-dir -r requirements.txt"
            OPEN_RUNTIMES_START_COMMAND: "python3 src/server.py"

          # Dart
          - ID: dart-3.3
            RUNTIME: dart
            VERSION: "3.3"
            ENTRYPOINT: lib/tests.dart
            INSTALL_COMMAND: "dart pub get"
            START_COMMAND: "src/function/server"
          - ID: dart-3.1
            RUNTIME: dart
            VERSION: "3.1"
            ENTRYPOINT: lib/tests.dart
            INSTALL_COMMAND: "dart pub get"
            START_COMMAND: "src/function/server"
          - ID: dart-3.0
            RUNTIME: dart
            VERSION: "3.0"
            ENTRYPOINT: lib/tests.dart
            INSTALL_COMMAND: "dart pub get"
            START_COMMAND: "src/function/server"
          - ID: dart-2.19
            RUNTIME: dart
            VERSION: "2.19"
            ENTRYPOINT: lib/tests.dart
            INSTALL_COMMAND: "dart pub get"
            START_COMMAND: "src/function/server"
          - ID: dart-2.18
            RUNTIME: dart
            VERSION: "2.18"
            ENTRYPOINT: lib/tests.dart
            INSTALL_COMMAND: "dart pub get"
            START_COMMAND: "src/function/server"
          - ID: dart-2.17
            RUNTIME: dart
            VERSION: "2.17"
            ENTRYPOINT: lib/tests.dart
            INSTALL_COMMAND: "dart pub get"
            START_COMMAND: "src/function/server"
          - ID: dart-2.16
            RUNTIME: dart
            VERSION: "2.16"
            ENTRYPOINT: lib/tests.dart
            INSTALL_COMMAND: "dart pub get"
            START_COMMAND: "src/function/server"
          - ID: dart-2.15
            RUNTIME: dart
            VERSION: "2.15"
            ENTRYPOINT: lib/tests.dart
            INSTALL_COMMAND: "dart pub get"
            START_COMMAND: "src/function/server"

          # Ruby
          - ID: ruby-3.3
            RUNTIME: ruby
            VERSION: "3.3"
            ENTRYPOINT: tests.rb
            INSTALL_COMMAND: ""
            START_COMMAND: "bundle exec puma -b tcp://0.0.0.0:3000 -e production"
          - ID: ruby-3.2
            RUNTIME: ruby
            VERSION: "3.2"
            ENTRYPOINT: tests.rb
            INSTALL_COMMAND: ""
            START_COMMAND: "bundle exec puma -b tcp://0.0.0.0:3000 -e production"
          - ID: ruby-3.1
            RUNTIME: ruby
            VERSION: "3.1"
            VERBOSE: ruby
            ENTRYPOINT: tests.rb
            INSTALL_COMMAND: ""
            START_COMMAND: "bundle exec puma -b tcp://0.0.0.0:3000 -e production"
          - ID: ruby-3.0
            RUNTIME: ruby
            VERSION: "3.0"
            ENTRYPOINT: tests.rb
            INSTALL_COMMAND: ""
            START_COMMAND: "bundle exec puma -b tcp://0.0.0.0:3000 -e production"

          # PHP
          - ID: php-8.0
            RUNTIME: php
            VERSION: "8.0"
            ENTRYPOINT: tests.php
            INSTALL_COMMAND: "composer update --no-interaction --ignore-platform-reqs --optimize-autoloader --prefer-dist --no-dev"
            START_COMMAND: "php src/server.php"
          - ID: php-8.1
            RUNTIME: php
            VERSION: "8.1"
            ENTRYPOINT: tests.php
            INSTALL_COMMAND: "composer update --no-interaction --ignore-platform-reqs --optimize-autoloader --prefer-dist --no-dev"
            START_COMMAND: "php src/server.php"
          - ID: php-8.2
            RUNTIME: php
            VERSION: "8.2"
            ENTRYPOINT: tests.php
            INSTALL_COMMAND: "composer update --no-interaction --ignore-platform-reqs --optimize-autoloader --prefer-dist --no-dev"
            START_COMMAND: "php src/server.php"
          - ID: php-8.3
            RUNTIME: php
            VERSION: "8.3"
            ENTRYPOINT: tests.php
            INSTALL_COMMAND: "composer update --no-interaction --ignore-platform-reqs --optimize-autoloader --prefer-dist --no-dev"
            START_COMMAND: "php src/server.php"

          # Swift
          - runtimes: swift-5.9
            RUNTIME: swift-5.9
            ENTRYPOINT: Tests.swift
            IMAGE: openruntimes/swift:v4-5.9
            ARCH: "linux/amd64,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "src/function/Runtime serve --env production --hostname 0.0.0.0 --port 3000"
          - runtimes: swift-5.8
            RUNTIME: swift-5.8
            ENTRYPOINT: Tests.swift
            IMAGE: openruntimes/swift:v4-5.8
            ARCH: "linux/amd64,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "src/function/Runtime serve --env production --hostname 0.0.0.0 --port 3000"
          - runtimes: swift-5.5
            RUNTIME: swift-5.5
            ENTRYPOINT: Tests.swift
            IMAGE: openruntimes/swift:v4-5.5
            ARCH: "linux/amd64,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "src/function/Runtime serve --env production --hostname 0.0.0.0 --port 3000"

          # Kotlin
          - runtimes: kotlin-1.9
            RUNTIME: kotlin-1.9
            ENTRYPOINT: Tests.kt
            IMAGE: openruntimes/kotlin:v4-1.9
            ARCH: "linux/amd64,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "java -jar src/function/kotlin-runtime-1.0.0.jar"
          - runtimes: kotlin-1.8
            RUNTIME: kotlin-1.8
            ENTRYPOINT: Tests.kt
            IMAGE: openruntimes/kotlin:v4-1.8
            ARCH: "linux/amd64,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "java -jar src/function/kotlin-runtime-1.0.0.jar"
          - runtimes: kotlin-1.6
            RUNTIME: kotlin-1.6
            ENTRYPOINT: Tests.kt
            IMAGE: openruntimes/kotlin:v4-1.6
            ARCH: "linux/amd64,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "java -jar src/function/kotlin-runtime-1.0.0.jar"

          # Java
          - runtimes: java-21.0
            RUNTIME: java-21.0
            ENTRYPOINT: Tests.java
            IMAGE: openruntimes/java:v4-21.0
            ARCH: "linux/amd64,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "java -jar src/function/java-runtime-1.0.0.jar"
          - runtimes: java-18.0
            RUNTIME: java-18.0
            ENTRYPOINT: Tests.java
            IMAGE: openruntimes/java:v4-18.0
            ARCH: "linux/amd64,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "java -jar src/function/java-runtime-1.0.0.jar"
          - runtimes: java-17.0
            RUNTIME: java-17.0
            ENTRYPOINT: Tests.java
            IMAGE: openruntimes/java:v4-17.0
            ARCH: "linux/amd64,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "java -jar src/function/java-runtime-1.0.0.jar"
          - runtimes: java-11.0
            RUNTIME: java-11.0
            ENTRYPOINT: Tests.java
            IMAGE: openruntimes/java:v4-11.0
            ARCH: "linux/amd64,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "java -jar src/function/java-runtime-1.0.0.jar"
          - runtimes: java-8.0
            RUNTIME: java-8.0
            ENTRYPOINT: Tests.java
            IMAGE: openruntimes/java:v4-8.0
            ARCH: "linux/amd64,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "java -jar src/function/java-runtime-1.0.0.jar"

          # C++
          - ID: cpp-20
            RUNTIME: cpp
            VERSION: "20"
            ENTRYPOINT: tests.cc
            INSTALL_COMMAND: ""
            START_COMMAND: "src/function/cpp_runtime"
          - ID: cpp-17
            RUNTIME: cpp
            VERSION: "17"
            ENTRYPOINT: tests.cc
            INSTALL_COMMAND: ""
            START_COMMAND: "src/function/cpp_runtime"

          # Dotnet
          - ID: dotnet-8.0
            RUNTIME: dotnet
            VERSION: "8.0"
            ENTRYPOINT: Tests.cs
            INSTALL_COMMAND: ""
            START_COMMAND: "dotnet src/function/DotNetRuntime.dll"
          - ID: dotnet-7.0
            RUNTIME: dotnet
            VERSION: "7.0"
            ENTRYPOINT: Tests.cs
            INSTALL_COMMAND: ""
            START_COMMAND: "dotnet src/function/DotNetRuntime.dll"
          - ID: dotnet-6.0
            RUNTIME: dotnet
            VERSION: "6.0"
            ENTRYPOINT: Tests.cs
            INSTALL_COMMAND: ""
            START_COMMAND: "dotnet src/function/DotNetRuntime.dll"

          # Bun
          - ID: bun-1.0
            RUNTIME: bun
            VERSION: "1.0"
            ENTRYPOINT: tests.ts
            INSTALL_COMMAND: "bun install"
            START_COMMAND: "bun src/server.ts"

          # Go
          - runtimes: go-1.22
            RUNTIME: go-1.22
            ENTRYPOINT: tests.go
            IMAGE: openruntimes/go:v4-1.22
            ARCH: "linux/amd64,linux/arm64"
            OPEN_RUNTIMES_BUILD_COMMAND: ""
            OPEN_RUNTIMES_START_COMMAND: "src/function/server"
    name: ${{ matrix.ID }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
      - name: Setup Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          mv composer.phar /usr/local/bin/composer
      - name: Install dependencies
        run: composer install
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run tests
        working-directory: ./
        run: sh ci_tests.sh
        env:
          RUNTIME: ${{ matrix.RUNTIME }}
          ENTRYPOINT: ${{ matrix.ENTRYPOINT }}
          VERSION: ${{ matrix.VERSION }}
          INSTALL_COMMAND: ${{ matrix.INSTALL_COMMAND }}
          START_COMMAND: ${{ matrix.START_COMMAND }}
